# -*- coding: utf-8 -*-
"""Prueba 2 Machine Learning.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M4_JA44LEVMv2FKGDKjezYpYwuWj8n7i
"""

# importa las librerías a nuestro entorno de trabajo
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

from google.colab import files
uploaded = files.upload()
for fn in uploaded.keys():
    name=fn
df1 = pd.read_pickle(name)

df = pd.DataFrame(df1)
df

newdataH= df1.iloc[:45,:]
newdataH

newData = df1.iloc[46:,:]
newData
newDataV2 = newData.T.reset_index()
newDataV2

newDataV2.columns = newDataV2.columns.to_flat_index().str.join('')
newDataV2

newDataV2['metadataSI'] = pd.to_numeric(newDataV2['metadataSI'])
newDataV2['metadataNO'] = pd.to_numeric(newDataV2['metadataNO'])

"""# **Medidas de Tendencia Central**

---

Variable: no
"""

#Media
newDataV2['metadataNO'].mean()

#Mediana
newDataV2['metadataNO'].median()

#Moda
newDataV2['metadataNO'].mode()

"""Variable: si"""

#Media
newDataV2['metadataSI'].mean()

#Mediana
newDataV2['metadataSI'].median()

#Moda
newDataV2['metadataSI'].mode()

"""# **Medidas de dispersión**

variable: si
"""

#Varianza
newDataV2['metadataSI'].var()

#Desviación estándar
newDataV2['metadataSI'].std()

#Cuartiles
newDataV2['metadataSI'].quantile([.25])

#Covarianza
newDataV2.cov()

newDataV2.plot.scatter(x = 'index', y= 'metadataNO')

#Coeficiente de correlación
newDataV2.corr()

#Resumen estadístico
newDataV2.describe()

"""variable: no"""

#Varianza
newDataV2['metadataNO'].var()

#Desviación estándar
newDataV2['metadataNO'].std()

#Cuartiles
newDataV2['metadataNO'].quantile([.25])

"""# **Graficos**"""

#Proyecto de ley, en tercer tramite constitucional, que modifica la ley N°20.551, 
#que regula el cierre de las faenas e instalaciones mineras. Enmiendas que propone 
#aprobar el informe de la Comisión de Minería y Energía.
newdataH[15].hist(bins=25)
newdataH[16].hist(bins=25)
plt.xlabel("Tipo de voto")
plt.ylabel("Cantidad de Votos")
plt.show()

disp=newDataV2.plot(kind='scatter',x='metadataSI', y='metadataNO')